# Generated by Django 4.2.1 on 2024-02-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('collegeName', models.CharField(blank=True, max_length=20, null=True)),
                ('collegeEmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
