# Generated by Django 4.2.1 on 2024-02-09 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_register_contactnumber_register_counsellingcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symName', models.CharField(blank=True, max_length=20, null=True)),
                ('guest', models.TextField(max_length=200)),
                ('Caption', models.CharField(blank=True, max_length=50, null=True)),
                ('collegeName', models.CharField(blank=True, max_length=100, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('RegistrationFee', models.IntegerField()),
                ('startdate', models.CharField(blank=True, max_length=20, null=True)),
                ('enddate', models.CharField(blank=True, max_length=20, null=True)),
                ('lastDate', models.CharField(blank=True, max_length=20, null=True)),
                ('eventType', models.CharField(blank=True, max_length=20, null=True)),
                ('Category', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('locationLink', models.CharField(blank=True, max_length=100, null=True)),
                ('eventLink', models.CharField(blank=True, max_length=100, null=True)),
                ('chatLink', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('Brouchure', models.ImageField(upload_to='')),
                ('postedDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='accountCreated',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
