# Generated by Django 4.2.1 on 2024-02-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_details_register_accountcreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='collegeImage',
            field=models.ImageField(default='defaultImages/college.jpeg', upload_to='collegeImages'),
        ),
        migrations.AlterField(
            model_name='details',
            name='Brouchure',
            field=models.ImageField(default='defaultImages/college.jpeg', upload_to='brochureImages'),
        ),
    ]
