# Generated by Django 4.2.1 on 2024-02-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_register_collegeimage_alter_details_brouchure'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
