# Generated by Django 4.2.1 on 2024-02-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_register_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='uniqueNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
