# Generated by Django 4.2.1 on 2024-02-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_details_uniquenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentMail', models.EmailField(blank=True, max_length=254, null=True)),
                ('yesOrNo', models.BooleanField(default=True)),
            ],
        ),
    ]
